---
title: "Projects"
---

In the summer of 2021 I took a GIS course called Introduction to Programming for GIS. This course introduced me to basic concepts for analyzing geospatial data using R. Below are a series of links for all the projects I completed in the course.

---
## [Building a project website](index.html)

- In this assignment I built a static users site with GitHub Pages.
- I learned how to navigate RStudio and use some basic functions to build a website.
- I was able to resolve error messages on my own to design a website to my preference but hope to continue improving my skills.

## [Data wrangling](https://oceanerouxx.github.io/geog-13-labs/lab-02.html)

- Utilized data manipulation skills to visualize real time COVID-19 data obtained from the New York Times
- Learned how to create faceted plots and ggplots to show COVID-19 trends US states
- Created a 7-day rolling mean of cases in New York, California, Louisiana, and Florida

## [Projections, Distances, and Mapping](https://oceanerouxx.github.io/geog-13-labs/lab-03.html)

- Manipulated data projections and spatial geometries
- Used st_distance to calculate the distance between US cities and borders of states and countries
- Learned the properties of sf, sfc, and sfg feature & objects

## [Tesselations, Spatial Joins, and Point-in-Polygon](https://oceanerouxx.github.io/geog-13-labs/lab-04.html)

- Visualized the distribution of dams and their purposes across the United States
- Learned how to use tessellation to simplify surfaces and geometry simplification to accelerate computing process
- Created functions and point-in-polygon counts to analyze point data
